/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.RoundedBorder;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author eduardo.schneider
 */
public class telaPrincipalUsuario extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipalUsuario
     */
    public telaPrincipalUsuario() {
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        this.setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null); //abre a tela no centro
        btnSaldo.setBorder(new RoundedBorder(15));
        btnSaldo.setForeground(Color.black);
        btnCDB.setBorder(new RoundedBorder(15));
        btnCDB.setForeground(Color.black);
        btnDeposito.setBorder(new RoundedBorder(15));
        btnDeposito.setForeground(Color.black);
        btnExtrato.setBorder(new RoundedBorder(15));
        btnExtrato.setForeground(Color.black);
        btnInvestimento.setBorder(new RoundedBorder(15));
        btnInvestimento.setForeground(Color.black);
        btnPagamento.setBorder(new RoundedBorder(15));
        btnPagamento.setForeground(Color.black);
        btnSaque.setBorder(new RoundedBorder(15));
        btnSaque.setForeground(Color.black);
        btnTransferencia.setBorder(new RoundedBorder(15));
        btnTransferencia.setForeground(Color.black);
        btnVoltar.setBorder(new RoundedBorder(15));
        btnVoltar.setForeground(Color.red);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDeposito = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();
        btnSaque = new javax.swing.JButton();
        btnPagamento = new javax.swing.JButton();
        btnTransferencia = new javax.swing.JButton();
        btnExtrato = new javax.swing.JButton();
        btnInvestimento = new javax.swing.JButton();
        btnCDB = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        btnDeposito.setBackground(new java.awt.Color(255, 255, 255));
        btnDeposito.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeposito.setText("Depósito");
        btnDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDepositoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDepositoMouseExited(evt);
            }
        });

        btnSaldo.setBackground(new java.awt.Color(255, 255, 255));
        btnSaldo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSaldo.setText("Saldo");
        btnSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaldoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaldoMouseExited(evt);
            }
        });

        btnSaque.setBackground(new java.awt.Color(255, 255, 255));
        btnSaque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSaque.setText("Saque(CC)");
        btnSaque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaqueMouseExited(evt);
            }
        });

        btnPagamento.setBackground(new java.awt.Color(255, 255, 255));
        btnPagamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPagamento.setText("Pagamento");
        btnPagamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPagamentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPagamentoMouseExited(evt);
            }
        });

        btnTransferencia.setBackground(new java.awt.Color(255, 255, 255));
        btnTransferencia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTransferencia.setText("Transferência");
        btnTransferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransferenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransferenciaMouseExited(evt);
            }
        });

        btnExtrato.setBackground(new java.awt.Color(255, 255, 255));
        btnExtrato.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExtrato.setText("Extrato");
        btnExtrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExtratoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExtratoMouseExited(evt);
            }
        });

        btnInvestimento.setBackground(new java.awt.Color(255, 255, 255));
        btnInvestimento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInvestimento.setText("Investimentos");
        btnInvestimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInvestimentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInvestimentoMouseExited(evt);
            }
        });

        btnCDB.setBackground(new java.awt.Color(255, 255, 255));
        btnCDB.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCDB.setText("CDB");
        btnCDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCDBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCDBMouseExited(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar.setText("Sair");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInvestimento, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(btnTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExtrato, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(btnCDB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCDB, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInvestimento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositoMouseEntered
        btnDeposito.setBackground(Color.black);
        btnDeposito.setForeground(Color.white);
    }//GEN-LAST:event_btnDepositoMouseEntered

    private void btnDepositoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDepositoMouseExited
        btnDeposito.setBackground(Color.white);
        btnDeposito.setForeground(Color.black);
    }//GEN-LAST:event_btnDepositoMouseExited

    private void btnPagamentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagamentoMouseEntered
        btnPagamento.setBackground(Color.black);
        btnPagamento.setForeground(Color.white);
    }//GEN-LAST:event_btnPagamentoMouseEntered

    private void btnPagamentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPagamentoMouseExited
        btnPagamento.setBackground(Color.white);
        btnPagamento.setForeground(Color.black);
    }//GEN-LAST:event_btnPagamentoMouseExited

    private void btnExtratoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExtratoMouseEntered
        btnExtrato.setBackground(Color.black);
        btnExtrato.setForeground(Color.white);
    }//GEN-LAST:event_btnExtratoMouseEntered

    private void btnExtratoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExtratoMouseExited
        btnExtrato.setBackground(Color.white);
        btnExtrato.setForeground(Color.black);
    }//GEN-LAST:event_btnExtratoMouseExited

    private void btnSaqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaqueMouseEntered
        btnSaque.setBackground(Color.black);
        btnSaque.setForeground(Color.white);
    }//GEN-LAST:event_btnSaqueMouseEntered

    private void btnSaqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaqueMouseExited
        btnSaque.setBackground(Color.white);
        btnSaque.setForeground(Color.black);
    }//GEN-LAST:event_btnSaqueMouseExited

    private void btnCDBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCDBMouseEntered
        btnCDB.setBackground(Color.black);
        btnCDB.setForeground(Color.white);
    }//GEN-LAST:event_btnCDBMouseEntered

    private void btnCDBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCDBMouseExited
        btnCDB.setBackground(Color.WHITE);
        btnCDB.setForeground(Color.black);
    }//GEN-LAST:event_btnCDBMouseExited

    private void btnSaldoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaldoMouseEntered
        btnSaldo.setBackground(Color.black);
        btnSaldo.setForeground(Color.white);
    }//GEN-LAST:event_btnSaldoMouseEntered

    private void btnSaldoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaldoMouseExited
        btnSaldo.setBackground(Color.white);
        btnSaldo.setForeground(Color.black);
    }//GEN-LAST:event_btnSaldoMouseExited

    private void btnInvestimentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvestimentoMouseEntered
        btnInvestimento.setBackground(Color.black);
        btnInvestimento.setForeground(Color.white);
    }//GEN-LAST:event_btnInvestimentoMouseEntered

    private void btnInvestimentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvestimentoMouseExited
        btnInvestimento.setBackground(Color.white);
        btnInvestimento.setForeground(Color.black);
    }//GEN-LAST:event_btnInvestimentoMouseExited

    private void btnTransferenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferenciaMouseEntered
        btnTransferencia.setBackground(Color.black);
        btnTransferencia.setForeground(Color.white);
    }//GEN-LAST:event_btnTransferenciaMouseEntered

    private void btnTransferenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferenciaMouseExited
        btnTransferencia.setBackground(Color.white);
        btnTransferencia.setForeground(Color.black);
    }//GEN-LAST:event_btnTransferenciaMouseExited

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        btnVoltar.setBackground(Color.red);
        btnVoltar.setForeground(Color.white);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        btnVoltar.setBackground(Color.white);
        btnVoltar.setForeground(Color.red);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.setVisible(false);
        new telaDeLogin().setVisible(true);
    }//GEN-LAST:event_btnVoltarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCDB;
    private javax.swing.JButton btnDeposito;
    private javax.swing.JButton btnExtrato;
    private javax.swing.JButton btnInvestimento;
    private javax.swing.JButton btnPagamento;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton btnSaque;
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
