/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.RoundedBorder;
import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author eduardo.schneider
 */
public class telaPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipalUsuario
     */
    public telaPrincipalAdmin() {
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        this.setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null); //abre a tela no centro
        btnInvestimentos.setBorder(new RoundedBorder(15));
        btnInvestimentos.setForeground(Color.black);
        btnPesquisaContas.setBorder(new RoundedBorder(15));
        btnPesquisaContas.setForeground(Color.black);
        btnCadastroCliente.setBorder(new RoundedBorder(15));
        btnCadastroCliente.setForeground(Color.black);
        btnPesquisaClientes.setBorder(new RoundedBorder(15));
        btnPesquisaClientes.setForeground(Color.black);
        btnPesquisaInvestimento.setBorder(new RoundedBorder(15));
        btnPesquisaInvestimento.setForeground(Color.black);
        btnCadastroConta.setBorder(new RoundedBorder(15));
        btnCadastroConta.setForeground(Color.black);
        btnAvancarODia.setBorder(new RoundedBorder(15));
        btnAvancarODia.setForeground(Color.black);
        btnVoltar.setBorder(new RoundedBorder(15));
        btnVoltar.setForeground(Color.red);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastroCliente = new javax.swing.JButton();
        btnInvestimentos = new javax.swing.JButton();
        btnCadastroConta = new javax.swing.JButton();
        lblInvestimentos = new javax.swing.JLabel();
        btnAvancarODia = new javax.swing.JButton();
        btnPesquisaInvestimento = new javax.swing.JButton();
        lblContas = new javax.swing.JLabel();
        btnPesquisaContas = new javax.swing.JButton();
        lblClientes = new javax.swing.JLabel();
        btnPesquisaClientes = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastroCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastroCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCadastroCliente.setText("Cadastrar Clientes");
        btnCadastroCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastroClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastroClienteMouseExited(evt);
            }
        });
        btnCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 28, 310, 86));

        btnInvestimentos.setBackground(new java.awt.Color(255, 255, 255));
        btnInvestimentos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInvestimentos.setText("Investimentos");
        btnInvestimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInvestimentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInvestimentosMouseExited(evt);
            }
        });
        jPanel1.add(btnInvestimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 236, 310, 86));

        btnCadastroConta.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastroConta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCadastroConta.setText("Cadastro Conta");
        btnCadastroConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastroContaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastroContaMouseExited(evt);
            }
        });
        jPanel1.add(btnCadastroConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 132, 310, 86));

        lblInvestimentos.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lblInvestimentos.setText("(Investimentos)");
        jPanel1.add(lblInvestimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 290, -1, -1));

        btnAvancarODia.setBackground(new java.awt.Color(255, 255, 255));
        btnAvancarODia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAvancarODia.setText("Avançar o Dia");
        btnAvancarODia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAvancarODiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAvancarODiaMouseExited(evt);
            }
        });
        jPanel1.add(btnAvancarODia, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 340, 300, 86));

        btnPesquisaInvestimento.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisaInvestimento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPesquisaInvestimento.setText("Pesquisa");
        btnPesquisaInvestimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisaInvestimentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisaInvestimentoMouseExited(evt);
            }
        });
        jPanel1.add(btnPesquisaInvestimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 236, 122, 86));

        lblContas.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lblContas.setText("(Contas)");
        jPanel1.add(lblContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 185, -1, -1));

        btnPesquisaContas.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisaContas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPesquisaContas.setText("Pesquisa");
        btnPesquisaContas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisaContasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisaContasMouseExited(evt);
            }
        });
        jPanel1.add(btnPesquisaContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 132, 122, 86));

        lblClientes.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lblClientes.setText("(Clientes)");
        jPanel1.add(lblClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        btnPesquisaClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisaClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPesquisaClientes.setText("Pesquisa");
        btnPesquisaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisaClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisaClientesMouseExited(evt);
            }
        });
        jPanel1.add(btnPesquisaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 28, 122, 86));

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnVoltar.setText("Sair");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 340, 140, 86));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroClienteMouseEntered
        btnCadastroCliente.setBackground(Color.black);
        btnCadastroCliente.setForeground(Color.white);
    }//GEN-LAST:event_btnCadastroClienteMouseEntered

    private void btnCadastroClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroClienteMouseExited
        btnCadastroCliente.setBackground(Color.white);
        btnCadastroCliente.setForeground(Color.black);
    }//GEN-LAST:event_btnCadastroClienteMouseExited

    private void btnPesquisaClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaClientesMouseEntered
        btnPesquisaClientes.setBackground(Color.black);
        btnPesquisaClientes.setForeground(Color.white);
        lblClientes.setForeground(Color.white);
    }//GEN-LAST:event_btnPesquisaClientesMouseEntered

    private void btnPesquisaClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaClientesMouseExited
        btnPesquisaClientes.setBackground(Color.white);
        btnPesquisaClientes.setForeground(Color.black);
        lblClientes.setForeground(Color.black);
    }//GEN-LAST:event_btnPesquisaClientesMouseExited

    private void btnCadastroContaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroContaMouseEntered
        btnCadastroConta.setBackground(Color.black);
        btnCadastroConta.setForeground(Color.white);
    }//GEN-LAST:event_btnCadastroContaMouseEntered

    private void btnCadastroContaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroContaMouseExited
        btnCadastroConta.setBackground(Color.white);
        btnCadastroConta.setForeground(Color.black);
    }//GEN-LAST:event_btnCadastroContaMouseExited

    private void btnPesquisaContasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaContasMouseEntered
        btnPesquisaContas.setBackground(Color.black);
        btnPesquisaContas.setForeground(Color.white);
        lblContas.setForeground(Color.white);
    }//GEN-LAST:event_btnPesquisaContasMouseEntered

    private void btnPesquisaContasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaContasMouseExited
        btnPesquisaContas.setBackground(Color.WHITE);
        btnPesquisaContas.setForeground(Color.black);
        lblContas.setForeground(Color.black);
    }//GEN-LAST:event_btnPesquisaContasMouseExited

    private void btnInvestimentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvestimentosMouseEntered
        btnInvestimentos.setBackground(Color.black);
        btnInvestimentos.setForeground(Color.white);
    }//GEN-LAST:event_btnInvestimentosMouseEntered

    private void btnInvestimentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvestimentosMouseExited
        btnInvestimentos.setBackground(Color.white);
        btnInvestimentos.setForeground(Color.black);
    }//GEN-LAST:event_btnInvestimentosMouseExited

    private void btnPesquisaInvestimentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaInvestimentoMouseEntered
        btnPesquisaInvestimento.setBackground(Color.black);
        btnPesquisaInvestimento.setForeground(Color.white);
        lblInvestimentos.setForeground(Color.white);
    }//GEN-LAST:event_btnPesquisaInvestimentoMouseEntered

    private void btnPesquisaInvestimentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaInvestimentoMouseExited
        btnPesquisaInvestimento.setBackground(Color.white);
        btnPesquisaInvestimento.setForeground(Color.black);
        lblInvestimentos.setForeground(Color.black);
    }//GEN-LAST:event_btnPesquisaInvestimentoMouseExited

    private void btnAvancarODiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvancarODiaMouseEntered
        btnAvancarODia.setBackground(Color.black);
        btnAvancarODia.setForeground(Color.white);
    }//GEN-LAST:event_btnAvancarODiaMouseEntered

    private void btnAvancarODiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvancarODiaMouseExited
        btnAvancarODia.setBackground(Color.white);
        btnAvancarODia.setForeground(Color.black);
    }//GEN-LAST:event_btnAvancarODiaMouseExited

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        btnVoltar.setBackground(Color.red);
        btnVoltar.setForeground(Color.white);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        btnVoltar.setBackground(Color.white);
        btnVoltar.setForeground(Color.red);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroClienteActionPerformed

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.setVisible(false);
        new telaDeLogin().setVisible(true);
    }//GEN-LAST:event_btnVoltarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancarODia;
    private javax.swing.JButton btnCadastroCliente;
    private javax.swing.JButton btnCadastroConta;
    private javax.swing.JButton btnInvestimentos;
    private javax.swing.JButton btnPesquisaClientes;
    private javax.swing.JButton btnPesquisaContas;
    private javax.swing.JButton btnPesquisaInvestimento;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblContas;
    private javax.swing.JLabel lblInvestimentos;
    // End of variables declaration//GEN-END:variables
}
