/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import banco.Cliente;
import banco.Poupanca;
import banco.RoundedBorder;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author eduardo.schneider
 */
public class telaPrincipalAdmin extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipalUsuario
     */
    public telaPrincipalAdmin() {
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); // Already there
        this.setUndecorated(true);
        this.setBackground(new Color(0,0,0,0));
        initComponents();
        setLocationRelativeTo(null); //abre a tela no centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fundo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fundo3 = new javax.swing.JLabel();
        fundo5 = new javax.swing.JLabel();
        fundo4 = new javax.swing.JLabel();
        fundo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAddPoupanca = new javax.swing.JButton();
        btnEXTRA = new javax.swing.JButton();
        btnPesquisaConta = new javax.swing.JButton();
        btnExcluirConta = new javax.swing.JButton();
        btnAddCdb = new javax.swing.JButton();
        btnCadastroConta = new javax.swing.JButton();
        btnAlterarConta = new javax.swing.JButton();
        btnAddInvestimento = new javax.swing.JButton();
        btnPoupanca = new javax.swing.JButton();
        btnCdb = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        btnPesquisaCliente = new javax.swing.JButton();
        btnCadastroCliente = new javax.swing.JButton();
        btnInvestimentos = new javax.swing.JButton();
        lblInvestimentos = new javax.swing.JLabel();
        btnAvancarODia = new javax.swing.JButton();
        btnAlterarClientes = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fundo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bank3.png"))); // NOI18N
        fundo1.setAlignmentX(0.5F);
        fundo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(fundo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 150, 130));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONTA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 90, 30));

        fundo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/negative.png"))); // NOI18N
        jPanel1.add(fundo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, 20));

        fundo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/negative.png"))); // NOI18N
        jPanel1.add(fundo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 20));

        fundo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        jPanel1.add(fundo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 20, 20));

        fundo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        jPanel1.add(fundo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 50, 20, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 110, 30));

        btnAddPoupanca.setBackground(new java.awt.Color(204, 255, 204));
        btnAddPoupanca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddPoupanca.setForeground(new java.awt.Color(0, 102, 51));
        btnAddPoupanca.setText("+");
        btnAddPoupanca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddPoupancaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddPoupancaMouseExited(evt);
            }
        });
        jPanel1.add(btnAddPoupanca, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 50, 86));

        btnEXTRA.setBackground(new java.awt.Color(255, 255, 255));
        btnEXTRA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEXTRA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEXTRAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEXTRAMouseExited(evt);
            }
        });
        jPanel1.add(btnEXTRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 350, 50));

        btnPesquisaConta.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisaConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisaConta.setText("Pesquisa");
        btnPesquisaConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisaContaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisaContaMouseExited(evt);
            }
        });
        jPanel1.add(btnPesquisaConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 110, 86));

        btnExcluirConta.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluirConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirConta.setText("Excluir");
        btnExcluirConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirContaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcluirContaMouseExited(evt);
            }
        });
        btnExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirContaActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluirConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 110, 86));

        btnAddCdb.setBackground(new java.awt.Color(204, 255, 204));
        btnAddCdb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddCdb.setForeground(new java.awt.Color(0, 102, 51));
        btnAddCdb.setText("+");
        btnAddCdb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddCdbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddCdbMouseExited(evt);
            }
        });
        jPanel1.add(btnAddCdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 116, 50, 110));

        btnCadastroConta.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastroConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadastroConta.setText("Cadastrar");
        btnCadastroConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastroContaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastroContaMouseExited(evt);
            }
        });
        btnCadastroConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroContaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastroConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 110, 86));

        btnAlterarConta.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterarConta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarConta.setText("Alterar");
        btnAlterarConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarContaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarContaMouseExited(evt);
            }
        });
        btnAlterarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarContaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 110, 86));

        btnAddInvestimento.setBackground(new java.awt.Color(204, 255, 204));
        btnAddInvestimento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddInvestimento.setForeground(new java.awt.Color(0, 102, 51));
        btnAddInvestimento.setText("+");
        btnAddInvestimento.setAlignmentX(0.5F);
        btnAddInvestimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddInvestimentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddInvestimentoMouseExited(evt);
            }
        });
        btnAddInvestimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInvestimentoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddInvestimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 50, 86));

        btnPoupanca.setBackground(new java.awt.Color(255, 255, 255));
        btnPoupanca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPoupanca.setText("Poupança");
        btnPoupanca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPoupancaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPoupancaMouseExited(evt);
            }
        });
        jPanel1.add(btnPoupanca, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 310, 86));

        btnCdb.setBackground(new java.awt.Color(255, 255, 255));
        btnCdb.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCdb.setText("CDB");
        btnCdb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCdbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCdbMouseExited(evt);
            }
        });
        jPanel1.add(btnCdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 116, 120, 110));

        btnExcluirCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluirCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExcluirClienteMouseExited(evt);
            }
        });
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnExcluirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 110, 86));

        btnPesquisaCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisaCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPesquisaCliente.setText("Pesquisa");
        btnPesquisaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisaClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisaClienteMouseExited(evt);
            }
        });
        jPanel1.add(btnPesquisaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 110, 86));

        btnCadastroCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastroCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCadastroCliente.setText("Cadastrar");
        btnCadastroCliente.setActionCommand("");
        btnCadastroCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastroClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastroClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastroClienteMouseExited(evt);
            }
        });
        jPanel1.add(btnCadastroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 86));

        btnInvestimentos.setBackground(new java.awt.Color(255, 255, 255));
        btnInvestimentos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnInvestimentos.setText("Investimentos");
        btnInvestimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInvestimentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInvestimentosMouseExited(evt);
            }
        });
        jPanel1.add(btnInvestimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 310, 86));

        lblInvestimentos.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lblInvestimentos.setText("(Investimentos)");
        jPanel1.add(lblInvestimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 290, -1, -1));

        btnAvancarODia.setBackground(new java.awt.Color(255, 255, 255));
        btnAvancarODia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAvancarODia.setText("Avançar o Dia");
        btnAvancarODia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAvancarODiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAvancarODiaMouseExited(evt);
            }
        });
        btnAvancarODia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarODiaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvancarODia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 350, 50));

        btnAlterarClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnAlterarClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarClientes.setText("Alterar");
        btnAlterarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarClientesMouseExited(evt);
            }
        });
        btnAlterarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarClientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 110, 86));

        btnVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnVoltar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnVoltar.setText("Sair");
        btnVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVoltarMouseExited(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 260, 110));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/112_hard.jpg"))); // NOI18N
        jPanel1.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 660, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 650, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroClienteMouseEntered
        btnCadastroCliente.setBackground(Color.black);
        btnCadastroCliente.setForeground(Color.white);
    }//GEN-LAST:event_btnCadastroClienteMouseEntered

    private void btnCadastroClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroClienteMouseExited
        btnCadastroCliente.setBackground(Color.white);
        btnCadastroCliente.setForeground(Color.black);
    }//GEN-LAST:event_btnCadastroClienteMouseExited

    private void btnAlterarClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarClientesMouseEntered
        btnAlterarClientes.setBackground(Color.black);
        btnAlterarClientes.setForeground(Color.white);
    }//GEN-LAST:event_btnAlterarClientesMouseEntered

    private void btnAlterarClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarClientesMouseExited
        btnAlterarClientes.setBackground(Color.white);
        btnAlterarClientes.setForeground(Color.black);
    }//GEN-LAST:event_btnAlterarClientesMouseExited

    private void btnInvestimentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvestimentosMouseEntered
        btnInvestimentos.setBackground(Color.black);
        btnInvestimentos.setForeground(Color.white);
    }//GEN-LAST:event_btnInvestimentosMouseEntered

    private void btnInvestimentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvestimentosMouseExited
        btnInvestimentos.setBackground(Color.white);
        btnInvestimentos.setForeground(Color.black);
    }//GEN-LAST:event_btnInvestimentosMouseExited

    private void btnAvancarODiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvancarODiaMouseEntered
        btnAvancarODia.setBackground(Color.black);
        btnAvancarODia.setForeground(Color.white);
    }//GEN-LAST:event_btnAvancarODiaMouseEntered

    private void btnAvancarODiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvancarODiaMouseExited
        btnAvancarODia.setBackground(Color.white);
        btnAvancarODia.setForeground(Color.black);
    }//GEN-LAST:event_btnAvancarODiaMouseExited

    private void btnVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseEntered
        btnVoltar.setBackground(Color.red);
        btnVoltar.setForeground(Color.white);
    }//GEN-LAST:event_btnVoltarMouseEntered

    private void btnVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseExited
        btnVoltar.setBackground(Color.white);
        btnVoltar.setForeground(Color.red);
    }//GEN-LAST:event_btnVoltarMouseExited

    private void btnVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVoltarMouseClicked
        this.setVisible(false);
        new telaDeLogin().setVisible(true);
    }//GEN-LAST:event_btnVoltarMouseClicked

    private void btnExcluirClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirClienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirClienteMouseEntered

    private void btnExcluirClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirClienteMouseExited

    private void btnPesquisaClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaClienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaClienteMouseEntered

    private void btnPesquisaClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaClienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaClienteMouseExited

    private void btnCdbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCdbMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCdbMouseEntered

    private void btnCdbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCdbMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCdbMouseExited

    private void btnPoupancaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPoupancaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoupancaMouseEntered

    private void btnPoupancaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPoupancaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoupancaMouseExited

    private void btnPesquisaContaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaContaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaContaMouseEntered

    private void btnPesquisaContaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisaContaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisaContaMouseExited

    private void btnExcluirContaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirContaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirContaMouseEntered

    private void btnExcluirContaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirContaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirContaMouseExited

    private void btnExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContaActionPerformed
        this.setVisible(false);
        new telaDeExcluirConta().setVisible(true);
    }//GEN-LAST:event_btnExcluirContaActionPerformed

    private void btnAlterarContaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarContaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarContaMouseEntered

    private void btnAlterarContaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarContaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarContaMouseExited

    private void btnEXTRAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEXTRAMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEXTRAMouseEntered

    private void btnEXTRAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEXTRAMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEXTRAMouseExited

    private void btnAddPoupancaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPoupancaMouseEntered
        btnAddPoupanca.setBackground(Color.green);
    }//GEN-LAST:event_btnAddPoupancaMouseEntered

    private void btnAddPoupancaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddPoupancaMouseExited
        btnAddPoupanca.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_btnAddPoupancaMouseExited

    private void btnAddCdbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCdbMouseEntered
        btnAddCdb.setBackground(Color.green);
    }//GEN-LAST:event_btnAddCdbMouseEntered

    private void btnAddCdbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCdbMouseExited
        btnAddCdb.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_btnAddCdbMouseExited

    private void btnAddInvestimentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddInvestimentoMouseEntered
        btnAddInvestimento.setBackground(Color.green);
    }//GEN-LAST:event_btnAddInvestimentoMouseEntered

    private void btnAddInvestimentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddInvestimentoMouseExited
        btnAddInvestimento.setBackground(new Color(204, 255, 204));
    }//GEN-LAST:event_btnAddInvestimentoMouseExited

    private void btnAddInvestimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInvestimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddInvestimentoActionPerformed

    private void btnCadastroClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroClienteMouseClicked
        this.setVisible(false);
        new telaDeCadastroDeCliente().setVisible(true);
    }//GEN-LAST:event_btnCadastroClienteMouseClicked

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        this.setVisible(false);
        new telaDeExcluirCliente().setVisible(true);
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void btnAlterarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarClientesActionPerformed
        this.setVisible(false);
        new telaDeAlterarCliente().setVisible(true);
    }//GEN-LAST:event_btnAlterarClientesActionPerformed

    private void btnAlterarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarContaActionPerformed
        this.setVisible(false);
        new telaDeAlterarConta().setVisible(true);
    }//GEN-LAST:event_btnAlterarContaActionPerformed

    private void btnAvancarODiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarODiaActionPerformed
        Connection con2;
        try {
            con2 = DriverManager.getConnection("jdbc:mysql://127.0.0.1/banco","root","");
            Statement stmt = (Statement)con2.createStatement();  
            String findCliente = "SELECT * FROM hoje";
            ResultSet resultSet = stmt.executeQuery(findCliente);
            LocalDate hoje = null;
            
            while (resultSet.next()){
                hoje = resultSet.getDate("data").toLocalDate();
                resultSet.close();
                break;
            } 
            hoje = hoje.plusDays(1);
            System.out.println(hoje.getDayOfMonth());
            Date hojeSQL = Date.valueOf(hoje);
            String aumentaData = "UPDATE hoje SET data = '" + hojeSQL + "' WHERE id = 1;";
            stmt.execute(aumentaData);
            Poupanca.verificaJurosBD();
        } catch (SQLException ex) {
            Logger.getLogger(telaPrincipalAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAvancarODiaActionPerformed

    private void btnCadastroContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroContaActionPerformed
        this.setVisible(false);
        new telaDeCadastroDeConta().setVisible(true);
    }//GEN-LAST:event_btnCadastroContaActionPerformed

    private void btnCadastroContaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroContaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroContaMouseExited

    private void btnCadastroContaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroContaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroContaMouseEntered

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCdb;
    private javax.swing.JButton btnAddInvestimento;
    private javax.swing.JButton btnAddPoupanca;
    private javax.swing.JButton btnAlterarClientes;
    private javax.swing.JButton btnAlterarConta;
    private javax.swing.JButton btnAvancarODia;
    private javax.swing.JButton btnCadastroCliente;
    private javax.swing.JButton btnCadastroConta;
    private javax.swing.JButton btnCdb;
    private javax.swing.JButton btnEXTRA;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnExcluirConta;
    private javax.swing.JButton btnInvestimentos;
    private javax.swing.JButton btnPesquisaCliente;
    private javax.swing.JButton btnPesquisaConta;
    private javax.swing.JButton btnPoupanca;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel fundo1;
    private javax.swing.JLabel fundo2;
    private javax.swing.JLabel fundo3;
    private javax.swing.JLabel fundo4;
    private javax.swing.JLabel fundo5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInvestimentos;
    // End of variables declaration//GEN-END:variables
}
